[Course Link - campusX](https://www.youtube.com/watch?v=zCDVUyq8lkw&list=PL2wfK7qZLX_P_XU-0ptmaf_Yk8vo7-voC)

[Pandas Playlist - DecodeAIML](https://www.youtube.com/watch?v=cpxi-ecMkVo&list=PLVyM62CSsh3W61sIg13KOQyrj_NDxC0on)

In [57]:
# import libraries

import pandas as pd
import numpy as np

In [58]:
# check pandas version

print(pd.__version__)

3.0.3

Pandas have built-in 2 data structures:
1. Series
2. DataFrame

**Key Features**

* Data cleaning - Handle missing values (fillna, dropna )
* Data selection & filtering - Use labels (loc ) or positions (iloc )
* Aggregation & grouping - groupby , sum, mean
* Merging & joining - Combine multiple datasets (merge, concat )
* Reshaping - Pivot tables, stack/unstack
* I/O operations - Read/write CSV, Excel, SQL, JSON, etc.

**Pandas vs NumPy - Which one to use and When?**

* **Dimension > 2**: Use **NumPy**
* Use NumPy (ndarray) when your **2-D data** is essentially a **numeric matrix** and you need fast, **memory-efficient** numerical work (linear algebra, broadcasting, heavy element wise operations).
* Use Pandas (DataFrame) when your **2-D data is a table** - i.e., columns with names, mixed d-types, missing values.
* Need for grouping/joins/time-series/CSV/Excel IO or easy selection by column name.

**Practical rule of Thumb**

* **Start** with Pandas for **data cleaning and exploration**.
* When doing **heavy numeric computations** (matrix factorization, linear algebra), **convert** the **numeric columns to a NumPy array.**

**Will Pandas work when data is larger than memory?**

Since Pandas **loads the entire dataset into memory**. if data is **larger than the main memory** here are practical approaches:

1. **[Dask](/dask/)** : A library that **extends** pandas with **parallel computing** and **chunked processing**.
2. **[Polars](/polars/)** : A fast **DataFrame library** written in **Rust**, with **lazy execution and streaming**.
3. **[PySpark](/pyspark/)** : A **distributed big-data engine**. PySpark **splits** the dataset into **chunks** (partitions) and processes them **sequentially** or in **parallel** - only a small chunk is in memory at a time.

## Series

Series is a **one-dimensional** array-like object containing an array of **various data-types**(integer, float, string, boolean, etc.) and an **associated array of data labels**, called its **index**.

Series is a buit-in Class in pandas.

In [59]:
# from list

countries:list[str] = ['India', 'USA', 'Russia', 'China', 'Brazil']
pd.Series(countries)

0     India
1       USA
2    Russia
3     China
4    Brazil
dtype: str

series have 2 things. One is data and other is index.

In [60]:
# from integers using np array

runs:np.ndarray = np.array([1,2,3,4,5])
pd.Series(runs, name="Serieswith_numbers")

0    1
1    2
2    3
3    4
4    5
Name: Serieswith_numbers, dtype: int64

In [61]:
# creating series with index
my_series = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
my_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [62]:
subjects:list[str] = ['Math', 'Science', 'English', 'Social', 'Coding']
marks:np.ndarray = np.array([95, 56, 78, 90, 96])

marks_series = pd.Series(marks, index=subjects)
marks_series

Math       95
Science    56
English    78
Social     90
Coding     96
dtype: int64

In [63]:
# setting a name for the series

marks_series = pd.Series(marks, index=subjects, name='StudentMarks')
marks_series

Math       95
Science    56
English    78
Social     90
Coding     96
Name: StudentMarks, dtype: int64

In [64]:
# creating series from dictionary

marks_dict: dict[str, int] = {'Math': 95, 'Science': 56, 'English': 78, 'Social': 90, 'Coding': 96}
marks_series:Series = pd.Series(marks_dict, name='StudentMarks_with_Dictionary')
marks_series

Math       95
Science    56
English    78
Social     90
Coding     96
Name: StudentMarks_with_Dictionary, dtype: int64

In [65]:
# series using read_csv

subject_mark_series = pd.read_csv('data/marks.csv')
# read_csv() always reads data as a DataFrame.
subject_mark_series

     subject  marks
0       Math     87
1    Science     72
2    English     91
3     Social     68
4     Coding     95
5    Physics     79
6  Chemistry     84
7    History     61
8  Geography     88
9    Biology     76

In [66]:
type(pd.read_csv('data/subs_count.csv').squeeze())

pandas.Series

In [67]:
# series using read_csv of 1 Column
subs = pd.read_csv('data/subs_count.csv').squeeze()
# .squeeze() converts a single-column DataFrame to a Series.
subs

# our meta data name is from the csv file, column name.

0     1250
1     3400
2      890
3    15200
4      420
5     6780
6     2100
7      985
8    11340
9      560
Name: subscribe_count, dtype: int64

In [68]:
# series using read_csv with 2 Columns

student_marks = pd.read_csv('data/marks.csv', index_col='subject').squeeze()
student_marks

subject
Math         87
Science      72
English      91
Social       68
Coding       95
Physics      79
Chemistry    84
History      61
Geography    88
Biology      76
Name: marks, dtype: int64

### series methods

In [69]:
# head()
subject_mark_series.head()

   subject  marks
0     Math     87
1  Science     72
2  English     91
3   Social     68
4   Coding     95

In [70]:
subject_mark_series.head(2)

   subject  marks
0     Math     87
1  Science     72

In [71]:
#tail()
subject_mark_series.tail()

     subject  marks
5    Physics     79
6  Chemistry     84
7    History     61
8  Geography     88
9    Biology     76

In [72]:
# value_counts()
subject_mark_series.value_counts()

subject    marks
Math       87       1
Science    72       1
English    91       1
Social     68       1
Coding     95       1
Physics    79       1
Chemistry  84       1
History    61       1
Geography  88       1
Biology    76       1
Name: count, dtype: int64

### series attributes

In [73]:
# series attributes apply to a Series, not a DataFrame
marks_series = pd.Series(marks_dict, name='StudentMarks_with_Dictionary')

In [74]:
# marks_series.size

marks_series.size # returns the number of elements in the series

5

In [75]:
# marks_series.dtype

marks_series.dtype # returns the data type of the series

dtype('int64')

In [76]:
# marks_series.nbytes

marks_series.nbytes # returns the number of bytes in the series

40

In [77]:
# marks_series.name

marks_series.name # returns the name of the series

'StudentMarks_with_Dictionary'

In [78]:
# marks_series.is_unique

marks_series.is_unique # returns True if the all items in the series are unique, otherwise False

True

In [79]:
marks_series.index

Index(['Math', 'Science', 'English', 'Social', 'Coding'], dtype='str')

In [80]:
marks_series.values # returns the values of the series in an numpy array

array([95, 56, 78, 90, 96])

### accessing elements by labels

In [81]:
print(my_series['a'])

1

In [82]:
print(my_series['b': 'd'])

b    2
c    3
d    4
dtype: int64

### accessing elements by index

In [83]:
print(my_series.iloc[0])

1

### add constant value to the each element of the series

In [84]:
my_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [85]:
my_series + 10

a    11
b    12
c    13
d    14
e    15
dtype: int64

In [86]:
#### add two series
my_series1 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
my_series2 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
my_series1 + my_series2

a     2
b     4
c     6
d     8
e    10
dtype: int64

## DataFrame

DataFrame is a **two-dimensional** array-like object containing an array of **various data-types**(integer, float, string, boolean, etc.) and an **associated array of data labels**, called its **index**.

In [96]:
student_data: dict[str, list[int] | list[str] | np.ndarray] = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': np.array([25, 30, 22, 35, 28]),
    'Score': np.array([85, 90, 78, 92, 88])
}
student_df = pd.DataFrame(student_data)
student_df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   22     78
3    David   35     92
4      Eva   28     88

In [102]:
student_df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 480.0 bytes

In [97]:
# extract Age column as a NumPy array (pandas 3.x: use to_numpy(), not .values)
age_array: np.ndarray = student_df['Age'].to_numpy()
age_array

array([25, 30, 22, 35, 28])

In [99]:
iris_data = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# this dataset have no header, so we need to specify column names
column_names: list[str] = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

iris_df = pd.read_csv(iris_data, header=None, names=column_names)
iris_df

iris_df.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [99]:
iris_df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    str
dtypes: float64(4), str(1)
memory usage: 13.9 KB

In [ ]:
# JSON
json_url = "https://jsonplaceholder.typicode.com/users"
json_df: pd.DataFrame = pd.read_json(json_url)
json_df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [106]:
json_df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        10 non-null     int64
 1   name      10 non-null     str
 2   username  10 non-null     str
 3   email     10 non-null     str
 4   address   10 non-null     object
 5   phone     10 non-null     str
 6   website   10 non-null     str
 7   company   10 non-null     object
dtypes: int64(1), object(2), str(5)
memory usage: 7.1 KB

In [121]:
# HTML

html_url = "https://en.wikipedia.org/wiki/List_of_countries_by_government_debt"
html_df: pd.DataFrame = pd.read_html(html_url,match='Country and region', storage_options={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'})[0]
html_df.head()

,Country and region,General government gross debt (2025)[6],Gross debt (2022)[7],Net debt (2021)[8]
0,Albania,54.3,67.581,64.1
1,Algeria,57.8,52.397,51.9
2,Andorra,32.0,38.788,NaN
3,Angola,64.5,67.050,NaN
4,Antigua and Barbuda,63.4,90.562,NaN

In [124]:
html_df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Country and region                       191 non-null    str
 1   General government gross debt (2025)[6]  191 non-null    str
 2   Gross debt (2022)[7]                     191 non-null    str
 3   Net debt (2021)[8]                       96 non-null     str
dtypes: str(4)
memory usage: 39.1 KB

In [125]:
html_df.describe()
#html_df.describe(include='int')
#html_df.describe(include='str')

,Country and region,General government gross debt (2025)[6],Gross debt (2022)[7],Net debt (2021)[8]
count,191,191,191,96
unique,191,163,190,87
top,Albania,–,-,-
freq,1,6,2,8

## 5.7.4 Box Plots

[box-plot - decodeaiml](https://youtu.be/JTdG9UlXyIM?si=I_6GSXfV_jb5Q7K0)

![box-plot](course_screenshots/box-plot.png "box-plot")

A **box plot** also Called whisker plot, is a powerful data visualization tool that provides Summary of a **numerical data distribution** in the Series.

It helps in:

* it uses boxes and lines to depict the data distribution
* Identifying outliers
* Understanding the distribution of the data
* Comparing multiple distributions

**Box Plot Components**
* Box: Represents the interquartile range (IQR)
* Whiskers: Extend to show the range of the data
* Median: The **middle value** of the data(50%) - It means that 50% data lies from Q1 to Q3(Called as IQR)
* Outliers: Points beyond the whiskers

![iqr](course_screenshots/iqr.png "iqr")

![iqr_1](course_screenshots/iqr_1.png "iqr_1")

![iqr-example](course_screenshots/iqr_example.png "iqr-example")

Let's understand key components of Box-Plot step by step.

1. Minimum (min) - Its not the lowest value in the data, but the lowest value that is not an outlier.
2. First Quartile (Q1) > Lower Quartile -> 25%th Percentile(it is not exactly 25%, but up to 25%)
3. Median (Q2) -> 50%th Percentile
4. Third Quartile (Q3) - Upper Quartile -> 75%th Percentile
5. Maximum (Max) - Its not the highest value in the data, but the highest value that is not an outlier.
6. Inter- Quartile range (IQR) -> Q3 - Q1
7. Outliers. -> Points beyond the whiskers

In [100]:
# create a sorted Pandas Series with default index

un_sorted_list: list[int] = [50, 10, 70, 30, 60, 20, 40]
sorted_series: Series = pd.Series(un_sorted_list).sort_values(ignore_index=True)
sorted_series

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [101]:
# find median(Q2) of the sorted_series

import statistics
statistics.median(sorted_series)

40

![min-value](course_screenshots/min_value.png "Minimum Value")

![max-value](course_screenshots/max_value.png "Maximum Value")

![outliers](course_screenshots/outliers.png "Outliers")