[Course Link](https://www.youtube.com/watch?v=zCDVUyq8lkw&list=PL2wfK7qZLX_P_XU-0ptmaf_Yk8vo7-voC)

In [144]:
# import libraries

import pandas as pd
import numpy as np

In [145]:
# check pandas version
import pandas as pd

print(pd.__version__)

3.0.3

Pandas have built-in 2 data structures:
1. Series
2. DataFrame

### creating series

Series is a **one-dimensional** array-like object containing an array of **various data-types**(integer, float, string, boolean, etc.) and an **associated array of data labels**, called its **index**.

Series is a buit-in Class in pandas.

In [146]:
# from list

countries:list[str] = ['India', 'USA', 'Russia', 'China', 'Brazil']
pd.Series(countries)

0     India
1       USA
2    Russia
3     China
4    Brazil
dtype: str

series have 2 things. One is data and other is index.

In [147]:
# from integers using np array

runs:np.ndarray = np.array([1,2,3,4,5])
pd.Series(runs, name="Serieswith_numbers")

0    1
1    2
2    3
3    4
4    5
Name: Serieswith_numbers, dtype: int64

In [148]:
# creating series with index
my_series = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
my_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [149]:
subjects:list[str] = ['Math', 'Science', 'English', 'Social', 'Coding']
marks:np.ndarray = np.array([95, 56, 78, 90, 96])

marks_series = pd.Series(marks, index=subjects)
marks_series

Math       95
Science    56
English    78
Social     90
Coding     96
dtype: int64

In [150]:
# setting a name for the series

marks_series = pd.Series(marks, index=subjects, name='StudentMarks')
marks_series

Math       95
Science    56
English    78
Social     90
Coding     96
Name: StudentMarks, dtype: int64

In [151]:
# creating series from dictionary

marks_dict: dict[str, int] = {'Math': 95, 'Science': 56, 'English': 78, 'Social': 90, 'Coding': 96}
marks_series:Series = pd.Series(marks_dict, name='StudentMarks_with_Dictionary')
marks_series

Math       95
Science    56
English    78
Social     90
Coding     96
Name: StudentMarks_with_Dictionary, dtype: int64

In [152]:
# series using read_csv

subject_mark_series = pd.read_csv('data/marks.csv')
# read_csv() always reads data as a DataFrame.
subject_mark_series

     subject  marks
0       Math     87
1    Science     72
2    English     91
3     Social     68
4     Coding     95
5    Physics     79
6  Chemistry     84
7    History     61
8  Geography     88
9    Biology     76

In [153]:
type(pd.read_csv('data/subs_count.csv').squeeze())

pandas.Series

In [ ]:
# series using read_csv of 1 Column
subs = pd.read_csv('data/subs_count.csv').squeeze()
# .squeeze() converts a single-column DataFrame to a Series.
subs

# our meta data name is from the csv file, column name.

0     1250
1     3400
2      890
3    15200
4      420
5     6780
6     2100
7      985
8    11340
9      560
Name: subscribe_count, dtype: int64

In [170]:
# series using read_csv with 2 Columns

student_marks = pd.read_csv('data/marks.csv', index_col='subject').squeeze()
student_marks

subject
Math         87
Science      72
English      91
Social       68
Coding       95
Physics      79
Chemistry    84
History      61
Geography    88
Biology      76
Name: marks, dtype: int64

### series mathods

In [171]:
# head()
subject_mark_series.head()

   subject  marks
0     Math     87
1  Science     72
2  English     91
3   Social     68
4   Coding     95

In [173]:
subject_mark_series.head(2)

   subject  marks
0     Math     87
1  Science     72

In [172]:
#tail()
subject_mark_series.tail()

     subject  marks
5    Physics     79
6  Chemistry     84
7    History     61
8  Geography     88
9    Biology     76

In [174]:
# value_counts()
subject_mark_series.value_counts()

subject    marks
Math       87       1
Science    72       1
English    91       1
Social     68       1
Coding     95       1
Physics    79       1
Chemistry  84       1
History    61       1
Geography  88       1
Biology    76       1
Name: count, dtype: int64

### series attributes

In [155]:
# series attributes apply to a Series, not a DataFrame
marks_series = pd.Series(marks_dict, name='StudentMarks_with_Dictionary')

In [156]:
# marks_series.size

marks_series.size # returns the number of elements in the series

5

In [157]:
# marks_series.dtype

marks_series.dtype # returns the data type of the series

dtype('int64')

In [158]:
# marks_series.nbytes

marks_series.nbytes # returns the number of bytes in the series

40

In [159]:
# marks_series.name

marks_series.name # returns the name of the series

'StudentMarks_with_Dictionary'

In [160]:
# marks_series.is_unique

marks_series.is_unique # returns True if the all items in the series are unique, otherwise False

True

In [161]:
marks_series.index

Index(['Math', 'Science', 'English', 'Social', 'Coding'], dtype='str')

In [162]:
marks_series.values # returns the values of the series in an numpy array

array([95, 56, 78, 90, 96])

### accessing elements by labels

In [163]:
print(my_series['a'])

1

In [164]:
print(my_series['b': 'd'])

b    2
c    3
d    4
dtype: int64

### accessing elements by index

In [165]:
print(my_series.iloc[0])

1

### add constant value to the each element of the series

In [166]:
my_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [167]:
my_series + 10

a    11
b    12
c    13
d    14
e    15
dtype: int64

In [168]:
#### add two series
my_series1 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
my_series2 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
my_series1 + my_series2

a     2
b     4
c     6
d     8
e    10
dtype: int64